apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-project
spec:
  replicas: 3

  selector:
    matchLabels:
      app: k8-project

  template:
    metadata:
      labels:
        app: k8-project

    spec:
      containers:
      - name: k8-project
        image: jcmp77/k8-project:latest

        ports:
        - containerPort: 3000 
